CREATE TABLE IF NOT EXISTS conversation (
    id              CHAR(32)     NOT NULL PRIMARY KEY COMMENT 'pk 32-char',
    chat_id         CHAR(32)     NOT NULL COMMENT 'biz chat id 32-char',
    user_id         CHAR(32)     NULL COMMENT 'user id 32-char',
    agent_type      VARCHAR(32)  NOT NULL COMMENT 'agent type',
    title           VARCHAR(128) NOT NULL,
    model           VARCHAR(64)  NULL,
    status          INT          NOT NULL DEFAULT 1 COMMENT '1=active 0=archived',
    create_date     DATETIME     NOT NULL COMMENT 'create time',
    create_by       VARCHAR(64)  NULL COMMENT 'create by',
    update_date     DATETIME     NOT NULL COMMENT 'update time',
    update_by       VARCHAR(64)  NULL COMMENT 'update by',
    is_del          TINYINT      NOT NULL DEFAULT 0 COMMENT '0=normal 1=deleted',
    enterprise_id   CHAR(32)     NULL COMMENT 'tenant id 32-char, no default',
    UNIQUE KEY uk_conversation_chat_id (chat_id),
    KEY idx_conversation_user_id (user_id),
    KEY idx_conversation_update_date (update_date),
    KEY idx_conversation_enterprise_id (enterprise_id),
    KEY idx_conversation_is_del (is_del)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='conversation';
