CREATE TABLE IF NOT EXISTS agent_trace (
    id                  CHAR(32)     NOT NULL PRIMARY KEY COMMENT '主键',
    trace_id            CHAR(32)     NOT NULL COMMENT '单次任务 TraceId',
    user_id             CHAR(32)     NULL COMMENT '用户ID',
    chat_id             CHAR(32)     NULL COMMENT '会话 chatId',
    agent_type          VARCHAR(32)  NULL COMMENT 'SUPER_AGENT / LOVE_MASTER 等',
    status              VARCHAR(32)  NOT NULL DEFAULT 'RUNNING' COMMENT 'RUNNING/SUCCESS/CANCELLED/ERROR',
    prompt_tokens       INT          NULL COMMENT '提示 Token',
    completion_tokens   INT          NULL COMMENT '补全 Token',
    total_tokens        INT          NULL COMMENT '总 Token',
    duration_ms         BIGINT       NULL COMMENT '端到端耗时毫秒',
    step_count          INT          NULL COMMENT '推理步数',
    error_message       VARCHAR(512) NULL COMMENT '错误摘要',
    create_date         DATETIME     NOT NULL COMMENT '创建时间',
    create_by           VARCHAR(64)  NULL COMMENT '创建人',
    update_date         DATETIME     NOT NULL COMMENT '更新时间',
    update_by           VARCHAR(64)  NULL COMMENT '更新人',
    is_del              TINYINT      NOT NULL DEFAULT 0 COMMENT '0=未删除 1=已删除',
    enterprise_id       CHAR(32)     NULL COMMENT '企业/租户ID',
    UNIQUE KEY uk_agent_trace_trace_id (trace_id),
    KEY idx_agent_trace_user_id (user_id),
    KEY idx_agent_trace_chat_id (chat_id),
    KEY idx_agent_trace_create_date (create_date),
    KEY idx_agent_trace_is_del (is_del)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent 单次任务 Trace';
